name: tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  phpunit:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['8.3', '8.2', '8.1', '8.0']
        laravel: ['9.*', '10.*', '11.*']
        dependency-version: [prefer-stable]
        include:
          - laravel: 9.*
            testbench: 7.*
          - laravel: 10.*
            testbench: 8.*
          - laravel: 11.*
            testbench: 9.*
        exclude:
          - laravel: 10.*
            php: 8.0
          - laravel: 11.*
            php: 8.1
          - laravel: 11.*
            php: 8.0

    name: P${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, zip, pcntl, bcmath, intl, exif
        coverage: xdebug

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

    - name: Run test phpunit
      run: vendor/bin/phpunit